// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txbyvyrwualiepwjnukm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4Ynl2eXJ3dWFsaWVwd2pudWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDc0NjcsImV4cCI6MjA3MjEyMzQ2N30.V-mgzRVbUmTRYUrcBg9xIVHFCff1hcUHI2_g59teKE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});